2024-04-03 22:05:23,665 Downloading artifacts
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m Unable to fetch artifact with name ketankishore28/NYC_AirBNB/random_forest_export:prod
Traceback (most recent call last):
  File "/Users/A118390615/opt/anaconda3/envs/mlflow-aca668dff4b4e454dd502d3d803604a064e08173/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/A118390615/opt/anaconda3/envs/mlflow-aca668dff4b4e454dd502d3d803604a064e08173/lib/python3.10/site-packages/wandb/apis/public.py", line 1040, in artifact
    artifact = wandb.Artifact._from_name(
  File "/Users/A118390615/opt/anaconda3/envs/mlflow-aca668dff4b4e454dd502d3d803604a064e08173/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 256, in _from_name
    raise ValueError(
ValueError: Unable to fetch artifact with name ketankishore28/NYC_AirBNB/random_forest_export:prod
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/A118390615/Desktop/udacity/udacity_mlops/components/test_regression_model/run.py", line 73, in <module>
    go(args)
  File "/Users/A118390615/Desktop/udacity/udacity_mlops/components/test_regression_model/run.py", line 27, in go
    model_local_path = run.use_artifact(args.mlflow_model).download()
  File "/Users/A118390615/opt/anaconda3/envs/mlflow-aca668dff4b4e454dd502d3d803604a064e08173/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/A118390615/opt/anaconda3/envs/mlflow-aca668dff4b4e454dd502d3d803604a064e08173/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/A118390615/opt/anaconda3/envs/mlflow-aca668dff4b4e454dd502d3d803604a064e08173/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2769, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/Users/A118390615/opt/anaconda3/envs/mlflow-aca668dff4b4e454dd502d3d803604a064e08173/lib/python3.10/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/Users/A118390615/opt/anaconda3/envs/mlflow-aca668dff4b4e454dd502d3d803604a064e08173/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/A118390615/opt/anaconda3/envs/mlflow-aca668dff4b4e454dd502d3d803604a064e08173/lib/python3.10/site-packages/wandb/apis/public.py", line 1040, in artifact
    artifact = wandb.Artifact._from_name(
  File "/Users/A118390615/opt/anaconda3/envs/mlflow-aca668dff4b4e454dd502d3d803604a064e08173/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 256, in _from_name
    raise ValueError(
wandb.errors.CommError: Unable to fetch artifact with name ketankishore28/NYC_AirBNB/random_forest_export:prod